name: Continuous Deployment
on:
  push:
    branches:
      - main
      - dev
concurrency: ${{ github.ref_name }}
jobs:
  deploy:
    runs-on: self-hosted
    environment: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - name: Minor version for each merge (Dry Run)
      id: taggerDryRun
      uses: anothrNick/github-tag-action@1.70.0
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        WITH_V: true
        DRY_RUN: true
        PRERELEASE: ${{ github.ref == 'refs/heads/dev' && 'true' || 'false' }}
        PRERELEASE_SUFFIX: 'dev'

    - name: Echo new tag
      run: echo "The next tag version will be ${{ steps.taggerDryRun.outputs.new_tag }}"

    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker pull jabriq/react-laravel:${{ steps.taggerDryRun.outputs.new_tag }}
          cd react-laravel
          sed -ir 's#laravel-react:v.*#laravel-react:${{ steps.taggerDryRun.outputs.new_tag }}#g' ./docker-compose.yml
          docker-compose down
          docker-compose up -d
          docker exec laravel-react-app php artisan migrate

    - name: Minor version for each merge (Final)
      id: taggerFinal
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        DRY_RUN: false
        WITH_V: true
